global:
  namespace: "guestbook"
  fullnameOverride: "guestbook"
  environment: {}
  replicaCount: 1

# serviceAccount:
#   enabled: true
#   name: guestbook-sa

image:
  repository: "gcr.io/heptio-images/ks-guestbook-demo"
  tag: "0.2"
  pullPolicy: Always

deployment:
  podAnnotations: {}
  command: []
  args: []

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%

service:
  type: NodePort
  specs:
    - name: http
      targetPort: 80
      port: 80
      protocol: TCP

nodeSelector:
  eks.amazonaws.com/nodegroup: sd2test-main-pvt-nodes

resources:
  requests:
    memory: "30Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "300m"

# secrets:
#   database-password:
#     key: "/path/to/your/secret/database-password"
#   api-key:
#     key: "/path/to/your/secret/api-key"
