
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argo-canary.fullname" . }}-app
  namespace: {{ .Values.global.namespace | quote }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "argo-canary.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  strategy:
    canary:
      steps:
        {{- range .Values.deployment.canarySteps }}
        - setWeight: {{ .weight }}
          {{- if .pause }}
        - pause: 
            duration: {{ .pause }}
          {{- end }}
        {{- end }}
  selector:
    matchLabels:
      {{- include "argo-canary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argo-canary.selectorLabels" . | nindent 8 }}
      {{- if .Values.deployment.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.deployment.podAnnotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "argo-canary.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.deployment.command }}
          command: {{ .Values.deployment.command }}
          {{- end }}
          {{- if .Values.deployment.args }}
          args: {{ .Values.deployment.args }}
          {{- end }}
          ports:
            {{- range .Values.service.specs }}
            - name: {{ .name }}
              containerPort: {{ .targetPort | default .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- if (merge .Values.global.environment .Values.deployment.environment) }}
          env:
            {{- range $name, $value := merge .Values.global.environment .Values.deployment.environment }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if and .Values.deployment.healthProbes.enabled .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if and .Values.deployment.healthProbes.enabled .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}

