apiVersion: v2
name: argo-canary
description: A Helm chart for deploying Argo Canary in Kubernetes, facilitating safe canary releases and traffic management.
type: application
version: 2.0.0
appVersion: "1.16.0"
dependencies:
  - name: lib-chart
    version: 1.0.0
    repository: file://../lib-chart
maintainers:
  - name: shristi-opstree
    email: shristi.gutpa@opstree.com